!------------------------------------------------------------------------------
! DRESP-09Z representation/audit bridge.
!
! This is intentionally an audit-only service.  It exposes the physical to
! product-rank map and the historical versus shadow six-branch candidate
! inventories without changing chi0, Dyson, or the production compact basis.
! A caller must supply the weighted radial arrays before making a numerical
! span claim; the dimension helpers do not fabricate a projection residual.
!------------------------------------------------------------------------------
module lr_dresp09z_bridge_mod

   implicit none
   private

   character(len=*), parameter, public :: dresp09z_pass_a = 'ARBITRARY_L_SR_VERTEX_CLOSED'
   character(len=*), parameter, public :: dresp09z_pass_b = &
      'RAW_ARBITRARY_L_VERTEX_CLOSED_PRODUCT_BASIS_EXTENSION_REQUIRED'
   character(len=*), parameter, public :: dresp09z_lower_open = 'LOWER_ANGULAR_RECOUPLING_OPEN'
   character(len=*), parameter, public :: dresp09z_tangent_open = 'AUGMENTATION_TANGENT_LM_OPEN'
   character(len=*), parameter, public :: dresp09z_duality_open = 'FIELD_DENSITY_DUALITY_OPEN'
   character(len=*), parameter, public :: dresp09z_mapping_open = 'PRODUCT_ANGULAR_MAPPING_OPEN'
   character(len=*), parameter, public :: dresp09z_mixed = 'MIXED'

   public :: dresp09z_historical_candidate_count
   public :: dresp09z_shadow_six_branch_candidate_count
   public :: dresp09z_source_product_ranks
   public :: dresp09z_allowed_orbital_pair

contains

   !> Historical four-branch candidate inventory, including all M blocks.
   pure integer function dresp09z_historical_candidate_count(orbital_lmax, response_lmax) result(value)
      integer, intent(in) :: orbital_lmax, response_lmax
      integer :: l, lp, response_l
      value = 0
      do response_l = 0, response_lmax
         do l = 0, orbital_lmax
            do lp = 0, orbital_lmax
               if (dresp09z_allowed_orbital_pair(l,lp,response_l)) value = value + 4*(2*response_l+1)
            end do
         end do
      end do
   end function dresp09z_historical_candidate_count

   !> Diagnostic shadow inventory with the complete six endpoint branches.
   pure integer function dresp09z_shadow_six_branch_candidate_count(orbital_lmax, response_lmax) result(value)
      integer, intent(in) :: orbital_lmax, response_lmax
      value = (6*dresp09z_historical_candidate_count(orbital_lmax,response_lmax))/4
   end function dresp09z_shadow_six_branch_candidate_count

   !> Product ranks K generated by source rank L x KH rank 2, with the
   !> retained orbital-product cutoff applied only to the returned diagnostic.
   pure subroutine dresp09z_source_product_ranks(source_l, orbital_product_lmax, ranks)
      integer, intent(in) :: source_l, orbital_product_lmax
      logical, intent(out) :: ranks(0:)
      integer :: product_l
      ranks = .false.
      if (source_l < 0) return
      do product_l = abs(source_l-2), source_l+2
         if (product_l <= ubound(ranks,1) .and. product_l <= orbital_product_lmax .and. &
             mod(source_l+2+product_l,2) == 0) ranks(product_l) = .true.
      end do
   end subroutine dresp09z_source_product_ranks

   pure logical function dresp09z_allowed_orbital_pair(l, lp, response_l) result(value)
      integer, intent(in) :: l, lp, response_l
      value = l >= 0 .and. lp >= 0 .and. response_l >= 0 .and. abs(l-lp) <= response_l .and. &
         response_l <= l+lp .and. mod(l+lp+response_l,2) == 0
   end function dresp09z_allowed_orbital_pair

end module lr_dresp09z_bridge_mod
