!------------------------------------------------------------------------------
! RS-LMTO-ASA
!------------------------------------------------------------------------------
!> @brief Independent Lounis/Costa/Muniz/Mills static sum-rule interaction.
!>
!> The route consumes a canonical LR-04 static chiKS and an explicitly supplied
!> Pauli number-spin magnetization.  It does not consume the direct ALSDA
!> kernel.  In the normalized L=0 response sector the LR-03 mapping is
!>
!>   m_00 = sqrt(4*pi) m_z,
!>   B_eff,00 = 4*pi U_LCMM m_00,
!>   Gamma U_LCMM = m_00,
!>   Gamma = 4*pi chiKS_00 diag(m_00).
!>
!> The origin is excluded from the solve because LR-04 assigns it exactly zero
!> volume measure.  Any remaining numerical rank deficiency is reported as a
!> blocker; no regularized interaction is promoted to production status.
!------------------------------------------------------------------------------
module lr_goldstone_sumrule_mod

   use precision_mod, only: rp
   use response_angular_basis_mod, only: response_angular_pi
   use response_basis_mapping_mod, only: response_super_index, response_flatten_superindex
   use lr_response_space_mod, only: response_space_layout, response_apply_operator, response_local_operator, &
      response_vector_norm, response_rigid_vector_overlap
   implicit none
   private

   character(len=*), parameter, public :: lr_gsr_magnetization_pauli = 'pauli_projected'
   character(len=*), parameter, public :: lr_gsr_route = 'goldstone_sumrule'
   character(len=*), parameter, public :: lr_gsr_units = 'Ry bohr^3'
   character(len=*), parameter, public :: lr_gsr_representation = &
      'LR-04 canonical interaction K_eff=4*pi*U_LCMM'
   real(rp), parameter, public :: lr_gsr_residual_tolerance = 1.0e-9_rp

   !> Request for the independent static sum-rule construction.
   type, public :: lr_goldstone_sumrule_request
      type(response_space_layout), pointer :: response_space => null()
      complex(rp), allocatable :: static_susceptibility(:, :) ! canonical LR-04 chiKS(0)
      real(rp), allocatable :: magnetization(:, :) ! physical m_z(site,r)
      character(len=32) :: magnetization_label = lr_gsr_magnetization_pauli
   end type lr_goldstone_sumrule_request

   !> Diagnostics and products of the sum-rule construction.
   type, public :: lr_goldstone_sumrule_result
      ! U_LCMM(site,r)=B_eff(site,r)/(4*pi*m_z(site,r)); origin is zero.
      complex(rp), allocatable :: u_lcmm(:, :)
      ! Pointwise LCMM energy splitting B_eff=4*pi*U_LCMM*m_z.
      complex(rp), allocatable :: effective_field(:, :)
      ! Canonical LR-04 local operator for B_eff,00=K_eff*m_00.
      complex(rp), allocatable :: canonical_interaction(:, :)
      ! Normalized response vector m_00=sqrt(4*pi)*m_z, origin excluded.
      complex(rp), allocatable :: magnetization_response(:)
      ! Full response-space B_eff,00 generated by K_eff acting on m_00.
      complex(rp), allocatable :: generated_field(:)
      complex(rp), allocatable :: generated_response(:)
      complex(rp), allocatable :: residual_vector(:)
      ! Gamma is the active spherical radial equation in the solve order.
      complex(rp), allocatable :: gamma(:, :)
      complex(rp), allocatable :: solution_active(:)
      real(rp), allocatable :: singular_values(:)
      integer :: rank = 0
      integer :: unknowns = 0
      real(rp) :: condition_number = huge(1.0_rp)
      real(rp) :: equation_residual_norm = huge(1.0_rp)
      real(rp) :: equation_relative_residual = huge(1.0_rp)
      real(rp) :: metric_residual_norm = huge(1.0_rp)
      real(rp) :: metric_relative_residual = huge(1.0_rp)
      complex(rp) :: rigid_overlap = cmplx(0.0_rp, 0.0_rp, rp)
      logical :: rank_deficient = .false.
      logical :: blocked = .true.
      character(len=32) :: route = lr_gsr_route
      character(len=32) :: magnetization_label = ''
      character(len=64) :: units = lr_gsr_units
      character(len=128) :: response_representation = lr_gsr_representation
      character(len=256) :: status = 'not evaluated'
   end type lr_goldstone_sumrule_result

   !> Result of the generic complex SVD solve Gamma*x=rhs.
   type, public :: lr_sumrule_linear_solve_result
      complex(rp), allocatable :: solution(:)
      real(rp), allocatable :: singular_values(:)
      integer :: rank = 0
      real(rp) :: condition_number = huge(1.0_rp)
      real(rp) :: residual_norm = huge(1.0_rp)
      real(rp) :: relative_residual = huge(1.0_rp)
      logical :: rank_deficient = .true.
      logical :: blocked = .true.
      character(len=256) :: status = 'not evaluated'
   end type lr_sumrule_linear_solve_result

   public :: evaluate_lr_goldstone_sumrule
   public :: solve_lr_goldstone_equation

   interface evaluate_lr_goldstone_sumrule
      module procedure evaluate_lr_goldstone_sumrule_request
      module procedure evaluate_lr_goldstone_sumrule_explicit
   end interface evaluate_lr_goldstone_sumrule

contains

   subroutine evaluate_lr_goldstone_sumrule_request(request, result)
      type(lr_goldstone_sumrule_request), intent(in) :: request
      type(lr_goldstone_sumrule_result), intent(out) :: result

      if (.not. associated(request%response_space)) then
         error stop 'evaluate_lr_goldstone_sumrule: response-space reference is incomplete'
      end if
      if (.not. allocated(request%static_susceptibility)) then
         error stop 'evaluate_lr_goldstone_sumrule: canonical static chiKS is required'
      end if
      if (.not. allocated(request%magnetization)) then
         error stop 'evaluate_lr_goldstone_sumrule: accepted magnetization is required explicitly'
      end if
      call evaluate_lr_goldstone_sumrule_explicit(request%response_space, request%static_susceptibility, &
         request%magnetization, result, request%magnetization_label)
   end subroutine evaluate_lr_goldstone_sumrule_request

   !> Evaluate the mapped LCMM equation using the canonical LR-04 chiKS.
   subroutine evaluate_lr_goldstone_sumrule_explicit(space, static_susceptibility, magnetization, result, &
                                                     magnetization_label)
      type(response_space_layout), intent(in) :: space
      complex(rp), intent(in) :: static_susceptibility(:, :)
      real(rp), intent(in) :: magnetization(:, :)
      type(lr_goldstone_sumrule_result), intent(out) :: result
      character(len=*), intent(in), optional :: magnetization_label

      type(lr_sumrule_linear_solve_result) :: solve
      complex(rp), allocatable :: target(:), field(:), response(:), residual(:)
      complex(rp), allocatable :: interaction_values(:, :), active_rhs(:)
      integer, allocatable :: active_indices(:)
      integer :: nunknown, isite, ir, i, j, flat, active_index
      real(rp) :: four_pi, target_metric_norm
      character(len=32) :: effective_label

      effective_label = lr_gsr_magnetization_pauli
      if (present(magnetization_label)) effective_label = trim(magnetization_label)
      call validate_inputs(space, static_susceptibility, magnetization, effective_label)

      four_pi = 4.0_rp*response_angular_pi
      nunknown = space%nsite*(space%npoint - 1)
      allocate(active_indices(nunknown), active_rhs(nunknown), result%gamma(nunknown, nunknown), &
               result%solution_active(nunknown), result%singular_values(nunknown))

      ! The active solve order is site-major, then positive-measure radial
      ! points.  It is deliberately derived through the LR-02R super-index.
      active_index = 0
      do isite = 1, space%nsite
         do ir = 2, space%npoint
            active_index = active_index + 1
            call l0_flat_index(space, isite, ir, active_indices(active_index))
            active_rhs(active_index) = cmplx(sqrt(four_pi)*magnetization(isite, ir), 0.0_rp, rp)
         end do
      end do

      ! LR-03 gives B_eff,00=4*pi*U_LCMM*m_00.  Since chiKS is already the
      ! LR-04 canonical B=chi_raw*W operator, no extra radial metric is
      ! inserted here: Gamma(:,j)=4*pi*chiKS(:,j)*m_00(j).
      do i = 1, nunknown
         do j = 1, nunknown
            result%gamma(i, j) = four_pi*static_susceptibility(active_indices(i), active_indices(j))* &
               active_rhs(j)
         end do
      end do

      call solve_lr_goldstone_equation(result%gamma, active_rhs, solve)
      result%solution_active = solve%solution
      result%singular_values = solve%singular_values
      result%rank = solve%rank
      result%unknowns = nunknown
      result%condition_number = solve%condition_number
      result%equation_residual_norm = solve%residual_norm
      result%equation_relative_residual = solve%relative_residual
      result%rank_deficient = solve%rank_deficient
      result%magnetization_label = effective_label

      allocate(result%u_lcmm(space%nsite, space%npoint), result%effective_field(space%nsite, space%npoint), &
               interaction_values(space%nsite, space%npoint), result%magnetization_response(space%ndim), &
               result%generated_field(space%ndim), result%generated_response(space%ndim), &
               result%residual_vector(space%ndim), target(space%ndim), field(space%ndim), response(space%ndim), &
               residual(space%ndim))
      result%u_lcmm = cmplx(0.0_rp, 0.0_rp, rp)
      result%effective_field = cmplx(0.0_rp, 0.0_rp, rp)
      result%magnetization_response = cmplx(0.0_rp, 0.0_rp, rp)
      result%generated_field = cmplx(0.0_rp, 0.0_rp, rp)
      result%generated_response = cmplx(0.0_rp, 0.0_rp, rp)
      result%residual_vector = cmplx(0.0_rp, 0.0_rp, rp)
      target = cmplx(0.0_rp, 0.0_rp, rp)
      field = cmplx(0.0_rp, 0.0_rp, rp)

      do isite = 1, space%nsite
         do ir = 2, space%npoint
            active_index = (isite - 1)*(space%npoint - 1) + ir - 1
            result%u_lcmm(isite, ir) = result%solution_active(active_index)
            result%effective_field(isite, ir) = four_pi*result%u_lcmm(isite, ir)*magnetization(isite, ir)
            call l0_flat_index(space, isite, ir, flat)
            target(flat) = active_rhs(active_index)
         end do
      end do

      interaction_values = cmplx(0.0_rp, 0.0_rp, rp)
      do isite = 1, space%nsite
         do ir = 2, space%npoint
            interaction_values(isite, ir) = four_pi*result%u_lcmm(isite, ir)
         end do
      end do
      allocate(result%canonical_interaction(space%ndim, space%ndim))
      call response_local_operator(space, interaction_values, result%canonical_interaction)
      result%magnetization_response = target
      ! Generate B_eff,00 through the canonical LR-04 action.  This keeps the
      ! production identity on one operator path and avoids a second local
      ! multiplication convention in this module.
      call response_apply_operator(space, result%canonical_interaction, target, field)
      result%generated_field = field
      call response_apply_operator(space, static_susceptibility, field, response)
      result%generated_response = response
      residual = response - target
      result%residual_vector = residual
      result%metric_residual_norm = response_vector_norm(space, residual)
      target_metric_norm = response_vector_norm(space, target)
      if (target_metric_norm > tiny(1.0_rp)) then
         result%metric_relative_residual = result%metric_residual_norm/target_metric_norm
      else
         result%metric_relative_residual = result%metric_residual_norm
      end if
      result%rigid_overlap = response_rigid_vector_overlap(space, residual, target)

      result%blocked = result%rank_deficient .or. result%metric_relative_residual > lr_gsr_residual_tolerance .or. &
         result%equation_relative_residual > lr_gsr_residual_tolerance
      if (result%rank_deficient) then
         result%status = 'BLOCKED: Gamma is numerically rank deficient'
      else if (result%metric_relative_residual > lr_gsr_residual_tolerance) then
         result%status = 'BLOCKED: full LR-04 Goldstone identity residual exceeds tolerance'
      else if (result%equation_relative_residual > lr_gsr_residual_tolerance) then
         result%status = 'BLOCKED: Gamma U=m residual exceeds tolerance'
      else
         result%blocked = .false.
         result%status = 'PASS: independent LCMM sum-rule identity'
      end if
   end subroutine evaluate_lr_goldstone_sumrule_explicit

   !> Solve a finite complex equation using an SVD-based least-squares kernel.
   !>
   !> RCOND=-1 asks LAPACK to use its machine-precision rank rule.  This is a
   !> numerical rank diagnostic, not a user-selected pseudoinverse cutoff.  A
   !> rank-deficient result is returned for inspection but marked BLOCKED by
   !> the production evaluator because LCMM does not select its null space.
   subroutine solve_lr_goldstone_equation(gamma, rhs, result)
      complex(rp), intent(in) :: gamma(:, :), rhs(:)
      type(lr_sumrule_linear_solve_result), intent(out) :: result

      complex(rp), allocatable :: a_work(:, :), b_work(:, :), work(:), work_query(:)
      real(rp), allocatable :: rwork(:)
      integer :: m, n, nrhs, ldb, lwork, info, i
      real(rp), parameter :: rcond = -1.0_rp
      real(rp) :: largest_singular, smallest_positive
      external :: zgelss

      m = size(gamma, 1)
      n = size(gamma, 2)
      nrhs = 1
      if (m < 1 .or. n < 1 .or. size(rhs) /= m) then
         error stop 'solve_lr_goldstone_equation: inconsistent Gamma/rhs shapes'
      end if
      ldb = max(1, max(m, n))
      allocate(a_work(m, n), b_work(ldb, nrhs), result%solution(n), &
               result%singular_values(min(m, n)), rwork(max(1, 5*min(m, n))))
      a_work = gamma
      b_work = cmplx(0.0_rp, 0.0_rp, rp)
      b_work(1:m, 1) = rhs
      allocate(work_query(1))
      call zgelss(m, n, nrhs, a_work, m, b_work, ldb, result%singular_values, rcond, result%rank, &
         work_query, -1, rwork, info)
      if (info /= 0) error stop 'solve_lr_goldstone_equation: LAPACK ZGELSS workspace query failed'
      lwork = max(1, int(real(work_query(1), rp)))
      allocate(work(lwork))
      a_work = gamma
      b_work = cmplx(0.0_rp, 0.0_rp, rp)
      b_work(1:m, 1) = rhs
      call zgelss(m, n, nrhs, a_work, m, b_work, ldb, result%singular_values, rcond, result%rank, &
         work, lwork, rwork, info)
      if (info /= 0) error stop 'solve_lr_goldstone_equation: LAPACK ZGELSS failed'
      result%solution = b_work(1:n, 1)

      largest_singular = maxval(result%singular_values)
      smallest_positive = huge(1.0_rp)
      do i = 1, size(result%singular_values)
         if (result%singular_values(i) > 0.0_rp) then
            smallest_positive = min(smallest_positive, result%singular_values(i))
         end if
      end do
      if (result%rank < min(m, n)) then
         result%condition_number = huge(1.0_rp)
      else if (smallest_positive < huge(1.0_rp)) then
         result%condition_number = largest_singular/smallest_positive
      end if
      result%residual_norm = sqrt(sum(abs(matmul(gamma, result%solution) - rhs)**2))
      if (sqrt(sum(abs(rhs)**2)) > tiny(1.0_rp)) then
         result%relative_residual = result%residual_norm/sqrt(sum(abs(rhs)**2))
      else
         result%relative_residual = result%residual_norm
      end if
      result%rank_deficient = result%rank < min(m, n)
      result%blocked = result%rank_deficient .or. result%relative_residual > lr_gsr_residual_tolerance
      if (result%rank_deficient) then
         result%status = 'BLOCKED: SVD numerical rank is below equation dimension'
      else if (result%relative_residual > lr_gsr_residual_tolerance) then
         result%status = 'BLOCKED: SVD equation residual exceeds tolerance'
      else
         result%blocked = .false.
         result%status = 'PASS: full-rank SVD solve'
      end if
   end subroutine solve_lr_goldstone_equation

   subroutine validate_inputs(space, static_susceptibility, magnetization, magnetization_label)
      type(response_space_layout), intent(in) :: space
      complex(rp), intent(in) :: static_susceptibility(:, :)
      real(rp), intent(in) :: magnetization(:, :)
      character(len=*), intent(in) :: magnetization_label
      integer :: isite, ir

      if (space%ndim < 1 .or. .not. allocated(space%radius) .or. .not. allocated(space%radial_weights) .or. &
          .not. allocated(space%metric_weights)) then
         error stop 'evaluate_lr_goldstone_sumrule: response space is not initialized'
      end if
      if (space%nchannel /= 1) then
         error stop 'evaluate_lr_goldstone_sumrule: one certified circular response channel is required'
      end if
      if (any(shape(static_susceptibility) /= [space%ndim, space%ndim])) then
         error stop 'evaluate_lr_goldstone_sumrule: static chiKS shape mismatch'
      end if
      if (any(shape(magnetization) /= [space%nsite, space%npoint])) then
         error stop 'evaluate_lr_goldstone_sumrule: magnetization shape mismatch'
      end if
      if (trim(magnetization_label) /= lr_gsr_magnetization_pauli) then
         error stop 'evaluate_lr_goldstone_sumrule: only the explicitly labelled Pauli magnetization is supported'
      end if
      do isite = 1, space%nsite
         do ir = 2, space%npoint
            if (magnetization(isite, ir) == 0.0_rp) then
               error stop 'evaluate_lr_goldstone_sumrule: zero Pauli magnetization on active grid; capability BLOCKED'
            end if
         end do
      end do
   end subroutine validate_inputs

   subroutine l0_flat_index(space, isite, ir, flat)
      type(response_space_layout), intent(in) :: space
      integer, intent(in) :: isite, ir
      integer, intent(out) :: flat
      type(response_super_index) :: item

      item = response_super_index(isite, 0, 0, ir, 1)
      call response_flatten_superindex(item, space%nsite, space%response_lmax, space%npoint, space%nchannel, flat)
   end subroutine l0_flat_index

end module lr_goldstone_sumrule_mod
