!------------------------------------------------------------------------------
! RS-LMTO-ASA
!------------------------------------------------------------------------------
!
! MODULE: Vacuum lead
!
! DESCRIPTION:
!> @brief
!> Generator for the frozen potential-parameter set of an empty-sphere
!> lattice -- the "vacuum lead" of B7 §1.6.
!>
!> ## What this is
!>
!> RS-LMTO-ASA does everything by embedding: a finite cluster with an active
!> interaction zone, surrounded by sites whose potential parameters are
!> *frozen* at values imported from a previous converged run. A "lead" is
!> nothing but a set of frozen parameters assigned to a subset of sites, and
!> a "vacuum Green function" is an ordinary Green function whose frozen
!> parameters happen to describe an empty lattice.
!>
!> The frozen parameter set for vacuum is the fixed point of an infinite
!> empty lattice: an empty sphere of radius w containing a **constant**
!> potential V0, rigidly shifted to the vacuum level. Today's surface path
!> instead hand-sets empty-sphere parameters; this module replaces that
!> pragmatic choice with a generated one.
!>
!> ## The one design constraint that matters (B7 §1.6)
!>
!> These parameters are generated by **the code's own radial solver driven
!> with V(r) = const**, not by hand-coded spherical-Bessel expressions. The
!> representation, the gamma/o convention, the E_nu convention and the
!> normalization then come out automatically consistent with every other
!> parameter set in the code, because they are produced by the very same
!> routine (`self%potpar`) that produces them for a real atom.
!>
!> The analytic free-electron result -- logarithmic derivatives of
!> j_l(kappa r) with kappa = sqrt(E - V0) -- is the **test oracle**
!> (`tests/unit/test_vacuum_lead.f90`, validation-ladder rung §5.5), *not*
!> the implementation. Reimplementing the Bessel expressions here and
!> testing them against themselves would defeat the entire point.
!>
!> ## Why it is a generator and not a table
!>
!> The parameters depend on the geometry -- the empty-sphere radius w, and
!> through it on the 2D lattice and the layer spacing -- so the set must be
!> produced per run from the run's own geometry. There are deliberately no
!> tabulated constants in this module.
!>
!> ## Honest limitation (B7 §1.6, stated here rather than discovered later)
!>
!> LMTO-ASA reproduces empty-lattice free-electron dispersion only over a
!> limited window above the band bottom; this is precisely the regime in
!> which the combined correction earns its keep. The frozen vacuum
!> parameters are therefore meaningful only if E_F sits **well below** the
!> vacuum band onset. That holds comfortably for ordinary metals and is
!> uncomfortable for very low work functions, so `check_fermi_margin`
!> warns when the margin is small.
!>
!> Do not oversell the payoff. For a good metal the evanescent decay
!> constant is kappa = sqrt(Phi) ~ 0.54 bohr^-1 for Phi ~ 4 eV, so vacuum
!> tails die within ~2 Angstrom -- which is exactly why one or two
!> hand-set empty-sphere layers already works. The vacuum lead is not
!> expected to move converged surface numbers much; its acceptance
!> criterion (B7 §5.6) is *reduced sensitivity to the empty-sphere layer
!> count*, not a changed answer. The real payoff is a well-defined vacuum
!> level, removal of an ad hoc convergence knob, and geometries where the
!> tail genuinely matters (vacuum-gap IEC, tunnelling barriers, low-DOS
!> spacers).
!>
!> ## Units (CONVENTIONS_MADELUNG.md C0 -- binding)
!>
!> Potential is in **Rydberg**, length in **bohr**, charge in electrons;
!> e^2 = 2 Ry*bohr. Every radius in this module (`ws_r`, `w`) is
!> **dimensional, in bohr** -- the `charge%wssurf(i)` convention, not the
!> dimensionless relative `charge%sws`. Mixing those two up is the single
!> easiest error in this code: for fccCu001, `sws ~ 0.391` (relative) while
!> `sws*alat*ang2au = 2.66899 bohr = wav*ang2au` (dimensional). This
!> module's constructor takes bohr.
!>
!> ## Scope
!>
!> **Self-contained. Nothing here is wired into any SCF path.** No
!> electrostatics, no decimation, no boundary self-energy, no k-space
!> route, no interface geometry. Consumers arrive with B7.3/B7.5.
!------------------------------------------------------------------------------
module vacuum_lead_mod
   use precision_mod, only: rp
   use logger_mod, only: g_logger
   use string_mod, only: real2str, int2str
   use self_mod, only: self
   use symbolic_atom_mod, only: symbolic_atom
   implicit none

   private

   !> Rydberg per electronvolt. The band-onset margin (§1.6) is a work
   !> function, which is quoted in eV in every source a user will consult,
   !> so the default threshold is expressed in eV and converted here.
   real(rp), parameter, public :: vacuum_lead_ry_per_ev = 1.0_rp/13.605693122994_rp

   !> Default margin below the vacuum band onset that counts as
   !> "comfortable", in Rydberg. 1 eV is a deliberately modest bar: a good
   !> metal clears it by several eV, and anything that fails it is a case
   !> where ASA empty-lattice dispersion is genuinely being asked for more
   !> than it can give.
   real(rp), parameter, public :: vacuum_lead_default_margin_ry = 1.0_rp*vacuum_lead_ry_per_ev

   !> How far inside the band bottom the default linearization point sits,
   !> as a step in the log derivative: `dnu = l - vacuum_lead_dnu_step`.
   !> The band bottom (kappa = 0) is at `dnu = l` exactly, so any positive
   !> value gives a propagating, node-free state; 0.5 puts E_nu in the
   !> lower part of the band for every l without crowding the edge. See
   !> `generate` for why the atomic path's uniform `pnu = l + 1.5` is not
   !> usable here.
   real(rp), parameter, public :: vacuum_lead_dnu_step = 0.5_rp

   !---------------------------------------------------------------------------
   !> Frozen potential-parameter set of an empty-sphere lattice.
   !>
   !> The stored parameters are exactly the set `self%potpar` produces, in
   !> the same convention: `enu`, `c`, `vl`, `srdel`, `qpar`, `ppar`,
   !> dimension (0:lmax, 2) -- l index and spin index. Both spin channels
   !> are generated and are identical by construction: vacuum is
   !> non-magnetic, and carrying the spin index anyway keeps the set
   !> shape-compatible with every other frozen set in the code, so a
   !> collinear FM/AFM lead stays a plain spin-index swap (B7 §5.8).
   !---------------------------------------------------------------------------
   type, public :: vacuum_lead
      !> Maximum angular momentum. Matches the active basis of the run
      !> whose vacuum this describes.
      integer :: lmax = 2
      !> Empty-sphere Wigner-Seitz radius, **bohr** (dimensional --
      !> `wssurf` convention, see C0 above).
      real(rp) :: ws_r = 0.0_rp
      !> Constant potential inside the sphere, Rydberg, on the run's
      !> absolute scale. This is the rigid shift to the vacuum level: the
      !> whole point of an empty-lattice reference is that V(r) has no
      !> r dependence, so a single scalar fixes it.
      real(rp) :: v0 = 0.0_rp
      !> Logarithmic-derivative boundary condition actually used, per l,
      !> as `pnu`. `dnu = tan(pi*(0.5 - pnu))` is what `potpar` consumes.
      !> Stored so the analytic oracle can be evaluated against the same
      !> boundary condition the solver was given.
      real(rp), dimension(:), allocatable :: pnu
      !> The same boundary condition as the log derivative `dnu` itself,
      !> which is the physically meaningful form: a node-free propagating
      !> state requires `dnu < l` (see `generate`). Redundant with `pnu`
      !> but stored because every statement about admissibility is natural
      !> in `dnu` and awkward in `pnu`.
      real(rp), dimension(:), allocatable :: dnu
      !> Radial-mesh parameters actually used, retained for the oracle and
      !> for diagnostics: `a` is the log-mesh parameter, `nr` the grid
      !> size, `rmax` the outermost mesh point (== ws_r to solver
      !> precision).
      real(rp) :: a = 0.0_rp
      integer :: nr = 0
      real(rp) :: rmax = 0.0_rp

      !> The generated set. Same shape and same meaning as
      !> `potential%enu` etc.
      real(rp), dimension(:, :), allocatable :: enu
      real(rp), dimension(:, :), allocatable :: c
      real(rp), dimension(:, :), allocatable :: vl
      real(rp), dimension(:, :), allocatable :: srdel
      real(rp), dimension(:, :), allocatable :: qpar
      real(rp), dimension(:, :), allocatable :: ppar

      !> .true. once `generate` has run successfully.
      logical :: generated = .false.
   contains
      procedure :: restore_to_default => vacuum_lead_restore_to_default
      procedure :: generate => vacuum_lead_generate
      procedure :: band_onset => vacuum_lead_band_onset
      procedure :: check_fermi_margin => vacuum_lead_check_fermi_margin
      procedure :: dump => vacuum_lead_dump
      final :: vacuum_lead_destructor
   end type vacuum_lead

   interface vacuum_lead
      procedure :: vacuum_lead_constructor
   end interface vacuum_lead

contains

   !---------------------------------------------------------------------------
   ! DESCRIPTION:
   !> @brief
   !> Constructor. Produces an un-generated set sized for `lmax`; call
   !> `generate` to fill it.
   !---------------------------------------------------------------------------
   function vacuum_lead_constructor(lmax) result(obj)
      type(vacuum_lead) :: obj
      integer, intent(in), optional :: lmax

      call obj%restore_to_default()
      if (present(lmax)) then
         obj%lmax = lmax
         call vacuum_lead_allocate(obj)
      end if
   end function vacuum_lead_constructor

   !---------------------------------------------------------------------------
   ! DESCRIPTION:
   !> @brief
   !> Destructor.
   !---------------------------------------------------------------------------
   subroutine vacuum_lead_destructor(this)
      type(vacuum_lead) :: this

      if (allocated(this%pnu)) deallocate (this%pnu)
      if (allocated(this%dnu)) deallocate (this%dnu)
      if (allocated(this%enu)) deallocate (this%enu)
      if (allocated(this%c)) deallocate (this%c)
      if (allocated(this%vl)) deallocate (this%vl)
      if (allocated(this%srdel)) deallocate (this%srdel)
      if (allocated(this%qpar)) deallocate (this%qpar)
      if (allocated(this%ppar)) deallocate (this%ppar)
   end subroutine vacuum_lead_destructor

   !---------------------------------------------------------------------------
   ! DESCRIPTION:
   !> @brief
   !> Reset all members to default: lmax = 2, nothing generated.
   !---------------------------------------------------------------------------
   subroutine vacuum_lead_restore_to_default(this)
      class(vacuum_lead), intent(inout) :: this

      if (allocated(this%pnu)) deallocate (this%pnu)
      if (allocated(this%dnu)) deallocate (this%dnu)
      if (allocated(this%enu)) deallocate (this%enu)
      if (allocated(this%c)) deallocate (this%c)
      if (allocated(this%vl)) deallocate (this%vl)
      if (allocated(this%srdel)) deallocate (this%srdel)
      if (allocated(this%qpar)) deallocate (this%qpar)
      if (allocated(this%ppar)) deallocate (this%ppar)

      this%lmax = 2
      this%ws_r = 0.0_rp
      this%v0 = 0.0_rp
      this%a = 0.0_rp
      this%nr = 0
      this%rmax = 0.0_rp
      this%generated = .false.

      call vacuum_lead_allocate(this)
   end subroutine vacuum_lead_restore_to_default

   !> Allocate the parameter arrays to the current lmax and zero them.
   subroutine vacuum_lead_allocate(this)
      class(vacuum_lead), intent(inout) :: this

      if (allocated(this%pnu)) deallocate (this%pnu)
      if (allocated(this%dnu)) deallocate (this%dnu)
      if (allocated(this%enu)) deallocate (this%enu)
      if (allocated(this%c)) deallocate (this%c)
      if (allocated(this%vl)) deallocate (this%vl)
      if (allocated(this%srdel)) deallocate (this%srdel)
      if (allocated(this%qpar)) deallocate (this%qpar)
      if (allocated(this%ppar)) deallocate (this%ppar)

      allocate (this%pnu(0:this%lmax))
      allocate (this%dnu(0:this%lmax))
      allocate (this%enu(0:this%lmax, 2))
      allocate (this%c(0:this%lmax, 2))
      allocate (this%vl(0:this%lmax, 2))
      allocate (this%srdel(0:this%lmax, 2))
      allocate (this%qpar(0:this%lmax, 2))
      allocate (this%ppar(0:this%lmax, 2))

      this%pnu = 0.0_rp
      this%dnu = 0.0_rp
      this%enu = 0.0_rp
      this%c = 0.0_rp
      this%vl = 0.0_rp
      this%srdel = 0.0_rp
      this%qpar = 0.0_rp
      this%ppar = 0.0_rp
   end subroutine vacuum_lead_allocate

   !---------------------------------------------------------------------------
   ! DESCRIPTION:
   !> @brief
   !> Generate the empty-lattice frozen parameter set for a sphere of
   !> radius `ws_r` holding a constant potential `v0`.
   !>
   !> ## How
   !>
   !> An empty sphere is set up as a Z = 0 `symbolic_atom` -- exactly the
   !> object every other parameter set in the code is generated from -- and
   !> `self%potpar` is called on it with a **constant** potential array.
   !> `potpar`'s solver (`RSEQSR`) treats the nuclear term separately, as
   !> `V(k) - 2*Z/r`, so with Z = 0 the potential the solver actually sees
   !> is exactly the constant `v0` and nothing else. That is the whole
   !> trick: no special-casing inside the solver, no parallel code path,
   !> and therefore no opportunity for the vacuum set to drift out of
   !> convention with the real-atom sets.
   !>
   !> ## Boundary condition
   !>
   !> `potpar` fixes the linearization energy E_nu per l by solving the
   !> radial equation at the logarithmic derivative
   !> `dnu = tan(pi*(0.5 - pnu))`, and takes the node count from
   !> `int(pnu) - l - 1`. For an empty lattice the natural choice is the
   !> lowest admissible principal quantum number `n = l + 1`, so zero
   !> radial nodes.
   !>
   !> The *fractional* part needs more care than "0.5 because that is
   !> free-electron-like". For a constant potential the log derivative of
   !> the regular solution is `D_l(x) = x j_l'(x)/j_l(x)` with `x = kappa w`,
   !> and `D_l(x -> 0) = l`, decreasing monotonically from there. So a
   !> propagating (E > V0), node-free state exists only for
   !>
   !>     D_l < l
   !>
   !> and `D_l = l` is exactly the band bottom, `kappa = 0`. The uniform
   !> `pnu = l + 1.5` used by the atomic path corresponds to `D = 0`, which
   !> is comfortably inside the window for l >= 1 but sits precisely *on*
   !> the l = 0 band bottom -- the solver duly returns `E_nu = V0` with
   !> `kappa = 0`, a degenerate linearization point.
   !>
   !> The default here is therefore fixed by the *physically* meaningful
   !> quantity, the log derivative, not by a fractional part carried over
   !> from atoms: `D_l = l - delta` with `delta = 0.5`, i.e. one fixed step
   !> inside the band bottom for every l. In `pnu` terms that is
   !> `pnu = l + 1 + 0.5 - atan(l - 0.5)/pi`. This is a *choice of
   !> linearization point*, not a physical constraint, and it is what the
   !> oracle checks against; `pnu` may be overridden per l by the caller
   !> when a different linearization is wanted.
   !>
   !> ## Geometry dependence
   !>
   !> `ws_r` is the only geometric input, and it carries the dependence on
   !> the 2D lattice and layer spacing: the empty-sphere radius is fixed by
   !> the volume the empty sphere has to fill. Nothing is tabulated.
   !>
   !> @param[in] solver  A `self` instance. `potpar` is a type-bound
   !>                     procedure but touches no component of `self`
   !>                     whatsoever -- it reads only `atom`, `V` and
   !>                     `ROFI` -- so a default-initialised instance is
   !>                     sufficient and no SCF context is implied.
   !> @param[in] ws_r    Empty-sphere Wigner-Seitz radius, **bohr**.
   !> @param[in] v0      Constant potential inside the sphere, **Rydberg**.
   !> @param[in] lmax    Maximum angular momentum. Optional; defaults to
   !>                     the object's current `lmax`.
   !> @param[in] pnu     Boundary condition per l, dimension(0:lmax).
   !>                     Optional; defaults to `l + 1.5`.
   !> @param[in] a       Log-mesh parameter. Optional; defaults to 0.02,
   !>                     the value the atomic path uses.
   !---------------------------------------------------------------------------
   subroutine vacuum_lead_generate(this, solver, ws_r, v0, lmax, pnu, a)
      class(vacuum_lead), intent(inout) :: this
      type(self), intent(inout) :: solver
      real(rp), intent(in) :: ws_r
      real(rp), intent(in) :: v0
      integer, intent(in), optional :: lmax
      real(rp), dimension(0:), intent(in), optional :: pnu
      real(rp), intent(in), optional :: a

      type(symbolic_atom) :: es
      real(rp), dimension(:, :), allocatable :: v
      real(rp), dimension(:), allocatable :: rofi
      real(rp) :: b, ea, rpb, pi
      integer :: ir, l, isp

      if (ws_r <= 0.0_rp) then
         call g_logger%fatal('vacuum_lead%generate: ws_r must be positive (bohr), got ' &
                             //real2str(ws_r), __FILE__, __LINE__)
      end if

      if (present(lmax)) this%lmax = lmax
      call vacuum_lead_allocate(this)

      this%ws_r = ws_r
      this%v0 = v0
      this%a = 0.02_rp
      if (present(a)) this%a = a

      ! Linearization point. A node-free propagating state in a constant
      ! potential requires dnu < l, with dnu = l exactly at the band
      ! bottom (kappa = 0). Take one fixed step inside that bound for
      ! every l, rather than inheriting the atomic path's uniform
      ! pnu = l + 1.5 (dnu = 0), which sits precisely ON the l = 0 band
      ! bottom and yields the degenerate E_nu = V0, kappa = 0.
      pi = 4.0_rp*atan(1.0_rp)
      do l = 0, this%lmax
         this%dnu(l) = real(l, rp) - vacuum_lead_dnu_step
         this%pnu(l) = real(l + 1, rp) + 0.5_rp - atan(this%dnu(l))/pi
      end do
      if (present(pnu)) then
         this%pnu(0:this%lmax) = pnu(0:this%lmax)
         do l = 0, this%lmax
            this%dnu(l) = tan(pi*(0.5_rp - this%pnu(l)))
         end do
      end if

      ! --- Set up the empty sphere as an ordinary Z = 0 symbolic_atom ---
      call es%element%restore_to_default()
      call es%potential%restore_to_default()
      es%element%symbol = 'Va'
      es%element%atomic_number = 0
      es%element%core = 0
      es%element%valence = 0
      es%element%num_quant_s = 1
      es%element%num_quant_p = 2
      es%element%num_quant_d = 3
      es%element%num_quant_f = 4
      es%A = this%a
      es%potential%ws_r = this%ws_r
      es%potential%lmax = this%lmax
      do isp = 1, 2
         do l = 0, this%lmax
            es%potential%pnu(l, isp) = this%pnu(l)
         end do
      end do

      ! --- The same logarithmic radial mesh atomsc builds ---
      this%nr = es%mesh_grid_size()
      b = es%B()
      allocate (rofi(this%nr), v(this%nr, 2))
      ea = exp(this%a)
      rpb = b
      do ir = 1, this%nr
         rofi(ir) = rpb - b
         rpb = rpb*ea
      end do
      this%rmax = rofi(this%nr)

      ! --- V(r) = const. This is the entire physical input. ---
      v = this%v0

      ! --- The code's own radial solver produces the parameter set ---
      call solver%potpar(es, v, rofi)

      do isp = 1, 2
         do l = 0, this%lmax
            this%enu(l, isp) = es%potential%enu(l, isp)
            this%c(l, isp) = es%potential%c(l, isp)
            this%vl(l, isp) = es%potential%vl(l, isp)
            this%srdel(l, isp) = es%potential%srdel(l, isp)
            this%qpar(l, isp) = es%potential%qpar(l, isp)
            this%ppar(l, isp) = es%potential%ppar(l, isp)
         end do
      end do

      this%generated = .true.
   end subroutine vacuum_lead_generate

   !---------------------------------------------------------------------------
   ! DESCRIPTION:
   !> @brief
   !> Onset of the vacuum band, in Rydberg, on the run's absolute scale.
   !>
   !> The empty lattice has no states below the bottom of its lowest (l = 0)
   !> band, and the LMTO band centre C is the natural estimate of where that
   !> band sits. The bottom of the s band is the relevant edge, so the onset
   !> is taken as the lowest band bottom over spin,
   !> `min_isp ( C(0,isp) - <band half-width> )`, with the half-width from
   !> the LMTO band-width parameter `srdel^2` scaled by the canonical
   !> s-band structure-constant bandwidth.
   !>
   !> This is deliberately a *conservative estimate for a warning*, not a
   !> spectral calculation: the honest statement (§1.6) is that ASA
   !> empty-lattice dispersion degrades some way above the band bottom, so a
   !> sharp number would be false precision. `C(0,·)` alone is the safe,
   !> defensible marker and is what is returned.
   !---------------------------------------------------------------------------
   function vacuum_lead_band_onset(this) result(onset)
      class(vacuum_lead), intent(in) :: this
      real(rp) :: onset

      if (.not. this%generated) then
         call g_logger%fatal('vacuum_lead%band_onset: parameters not generated yet', &
                             __FILE__, __LINE__)
      end if

      onset = min(this%c(0, 1), this%c(0, 2))
   end function vacuum_lead_band_onset

   !---------------------------------------------------------------------------
   ! DESCRIPTION:
   !> @brief
   !> Warn when E_F is not comfortably below the vacuum band onset
   !> (B7 §1.6, the honest-limitation paragraph).
   !>
   !> The frozen vacuum parameters are only meaningful while E_F sits well
   !> below the onset of the empty-lattice band: LMTO-ASA reproduces
   !> free-electron dispersion over a limited window above the band bottom,
   !> and above that window an empty-lattice reference is being asked for
   !> more than it can deliver. Ordinary metals clear this comfortably; very
   !> low work functions do not.
   !>
   !> Emits a warning -- not a fatal -- because a small margin degrades
   !> accuracy rather than invalidating the run, and because the user may
   !> legitimately be probing exactly that regime. Silence would be the
   !> failure mode worth avoiding.
   !>
   !> @param[in] fermi_energy  E_F, Rydberg, on the same absolute scale as
   !>                           `v0`.
   !> @param[in] margin        Required margin, Rydberg. Optional; defaults
   !>                           to `vacuum_lead_default_margin_ry` (1 eV).
   !> @return .true. if the margin is comfortable.
   !---------------------------------------------------------------------------
   function vacuum_lead_check_fermi_margin(this, fermi_energy, margin) result(ok)
      class(vacuum_lead), intent(in) :: this
      real(rp), intent(in) :: fermi_energy
      real(rp), intent(in), optional :: margin
      logical :: ok
      real(rp) :: margin_, onset, actual

      margin_ = vacuum_lead_default_margin_ry
      if (present(margin)) margin_ = margin

      onset = this%band_onset()
      actual = onset - fermi_energy
      ok = (actual >= margin_)

      if (.not. ok) then
         call g_logger%warning('vacuum_lead: E_F is not comfortably below the vacuum band onset. ' &
                               //'E_F = '//real2str(fermi_energy)//' Ry, onset = '//real2str(onset) &
                               //' Ry, margin = '//real2str(actual)//' Ry ('// &
                               real2str(actual/vacuum_lead_ry_per_ev)//' eV), required ' &
                               //real2str(margin_)//' Ry. LMTO-ASA reproduces empty-lattice ' &
                               //'free-electron dispersion only over a limited window above the ' &
                               //'band bottom, so the frozen vacuum parameters lose meaning as ' &
                               //'E_F approaches the onset. Typical for very low work functions; ' &
                               //'treat vacuum-side results with corresponding caution.', &
                               __FILE__, __LINE__)
      end if
   end function vacuum_lead_check_fermi_margin

   !---------------------------------------------------------------------------
   ! DESCRIPTION:
   !> @brief
   !> Dump the generated set for debugging, in the same layout as the
   !> potential-parameter tables elsewhere.
   !---------------------------------------------------------------------------
   subroutine vacuum_lead_dump(this, unit)
      class(vacuum_lead), intent(in) :: this
      integer, intent(in), optional :: unit
      integer :: u, l, isp

      u = 6
      if (present(unit)) u = unit

      write (u, '(a)') '--- vacuum_lead: empty-lattice frozen parameter set ---'
      write (u, '(a,f12.6,a)') '  ws_r  = ', this%ws_r, ' bohr'
      write (u, '(a,f12.6,a)') '  v0    = ', this%v0, ' Ry'
      write (u, '(a,i0)') '  lmax  = ', this%lmax
      write (u, '(a,f12.6,a,i0,a,f12.6)') '  a     = ', this%a, '   nr = ', this%nr, &
         '   rmax = ', this%rmax
      if (.not. this%generated) then
         write (u, '(a)') '  (not generated)'
         return
      end if
      write (u, '(a,f12.6,a)') '  band onset (C_s) = ', this%band_onset(), ' Ry'
      write (u, '(a)') '  isp   l        pnu         enu           C          VL       SRDEL        QPAR        PPAR'
      do isp = 1, 2
         do l = 0, this%lmax
            write (u, '(2i5,7f12.6)') isp, l, this%pnu(l), this%enu(l, isp), this%c(l, isp), &
               this%vl(l, isp), this%srdel(l, isp), this%qpar(l, isp), this%ppar(l, isp)
         end do
      end do
   end subroutine vacuum_lead_dump

end module vacuum_lead_mod
