#!/usr/bin/env python3
"""Analytic and semi-analytic references A1-A3 for the spin_response C0 kernels.

Developer-owned oracle: generated by this script, reviewed by the developer,
committed under tests/spin_response/oracles/, read-only to AI sessions.

Conventions (spec, section "Conventions"):
  sigma+ = |up><dn|, no factor 2; Kubo sign; energies, omega, eta, U in Ry.
  chi0_ij(q,w) = sum_k w_k sum_{n,m} (f_nk - f_m,k+q) T_i T_j^* / (w + e_nk - e_m,k+q + i eta)
  T_i^{nm}     = sum_{mu in d} conj(a^{nk}_{i mu up}) a^{m,k+q}_{i mu dn}
  (I + chi0 U) chi = chi0,  U > 0 diagonal in sites,  Goldstone chi0(0,0) U M = -M
  L = -(chi - chi^H)/(2 pi i); one site: -Im chi / pi.

What each model anchors:
  A1  two-level, closed form.  Exact pole at delta*Delta; Mills variant.
  A2  self-consistent single band (5 degenerate orbitals, site U coupling the
      total moment), partially polarized (86%), so both spin bands are
      occupied at both endpoints.  Exact anchor: chi0(0,0) = -1/U at eta -> 0
      for any mesh and temperature.  Finite-q values are an independent
      evaluation of the spec formula (numpy, vectorized), not an analytic
      result.  Its magnons are very soft (about 4e-7 Ry at the smallest q), so
      magnon_eta0 is informational only; pole finding (C6) is tested by A1.
  A3  A2 on a doubled cell.  Exact anchor: the gauge-invariant cell response
      equals A2 at Q and Q + G_super.  Band phases are randomized, so the
      kernels must be phase-invariant to pass.

Output: one Fortran namelist file per model.  Complex arrays are written as
separate _re and _im arrays, in Fortran (column-major) order; each file states
its array dimensions and amplitude rule in string keys.  Only numpy is needed.

Suggested tolerances (the developer sets the final ones):
  A1 arrays and scalars          1e-12 relative (closed form)
  A2 chi0, chi arrays            1e-10 relative (different summation order)
  A2 Goldstone, zeroth moment    1e-12 relative (exact identities)
  A3 trace, determinant          1e-10 relative (self-check reaches ~1e-14)

Usage: python3 make_references.py [outdir]
"""
import sys
from pathlib import Path

import numpy as np

NORB = 5            # degenerate d copies for A1 and A2
NORB_A3 = 1         # orbital count for A3 (kernels must take it from the array shape)
ETA = 1.0e-3        # broadening for the finite-eta outputs (Ry)
ETA_STATIC = (4.0e-3, 2.0e-3, 1.0e-3, 5.0e-4)


# ----------------------------------------------------------------------------
# helpers
# ----------------------------------------------------------------------------
def fermi(e, ef, kt):
    """Fermi-Dirac occupation, stable form."""
    return 0.5 * (1.0 - np.tanh(0.5 * (e - ef) / kt))


def lehmann_pairs(w, de, weight, omega, eta):
    """sum_p weight_p * w_p / (omega + de_p + i eta), de_p = e_n - e_m.

    w, de, weight: arrays over pairs; omega: 1-D grid.  Returns complex array.
    """
    num = (w * weight)[None, :]
    den = omega[:, None] + de[None, :] + 1j * eta
    return (num / den).sum(axis=1)


def lehmann_static_eta0(w, f_n, f_m, e_n, e_m, kt, weight):
    """Same sum at omega = 0, eta = 0, with Fermi divided differences."""
    de = e_n - e_m
    out = np.empty_like(de)
    big = np.abs(de) > 1.0e-10
    out[big] = (f_n[big] - f_m[big]) / de[big]
    # (f_n - f_m)/(e_n - e_m) -> f'(e) = -f(1-f)/kT for degenerate pairs
    fe = f_n[~big]
    out[~big] = -fe * (1.0 - fe) / kt
    return float((w * weight * out).sum())


def window_moment(w, de, weight, eta, wa, wb):
    """Exact integral over [wa, wb] of -Im(sum)/pi for the finite-eta sum.

    Each pair is a Lorentzian at omega_p = -de_p with weight w*weight.
    """
    om = -de
    return float((w * weight * (np.arctan((wb - om) / eta)
                                - np.arctan((wa - om) / eta))).sum() / np.pi)


def bisect(fun, a, b, tol=1.0e-15, itmax=300):
    fa = fun(a)
    for _ in range(itmax):
        c = 0.5 * (a + b)
        fc = fun(c)
        if (fc > 0) == (fa > 0):
            a, fa = c, fc
        else:
            b = c
        if b - a < tol:
            break
    return 0.5 * (a + b)


def nml_value(v):
    if isinstance(v, (bool, np.bool_)):
        return ".true." if v else ".false."
    if isinstance(v, (int, np.integer)):
        return str(int(v))
    if isinstance(v, str):
        return "'" + v + "'"
    return f"{float(v):.17e}"


def write_group(fh, name, items):
    fh.write(f"&{name}\n")
    for key, val in items:
        arr = np.asarray(val)
        if arr.ndim == 0:
            fh.write(f"  {key} = {nml_value(val)}\n")
        else:
            flat = arr.ravel(order="F")
            fh.write(f"  {key} =\n")
            for i in range(0, flat.size, 4):
                fh.write("    " + ", ".join(nml_value(x) for x in flat[i:i + 4]) + ",\n")
    fh.write("/\n\n")


def check(label, value, tol):
    status = "ok" if abs(value) <= tol else "FAIL"
    print(f"  [{status}] {label}: {value:.3e} (tol {tol:.0e})")
    if status == "FAIL":
        raise SystemExit(f"self-check failed: {label}")


# ----------------------------------------------------------------------------
# A1: two-level, closed form
# ----------------------------------------------------------------------------
def model_a1(outdir):
    print("A1 two-level")
    delta = 0.15                      # level splitting e_dn - e_up (Ry)
    dfrac = 0.0612                    # Goldstone residual; pole lies 0.36 grid steps off-grid
    mills_factor = 0.9                # band-centre splitting / level splitting (variant)
    m = float(NORB)                   # moment: NORB occupied up levels, empty down
    omega = np.linspace(-0.05, 0.25, 601)

    u_gold = delta / m
    u_test = (1.0 - dfrac) * delta / m
    chi0 = NORB / (omega - delta + 1j * ETA)
    chi = chi0 / (1.0 + chi0 * u_test)
    pole = dfrac * delta
    chi_closed = NORB / (omega - pole + 1j * ETA)
    check("chi from Dyson vs closed form 5/(w - d*Delta + i eta)",
          np.max(np.abs(chi - chi_closed)) / np.max(np.abs(chi_closed)), 1e-13)

    u_mills_var = mills_factor * delta / m
    resid_mills_var = 1.0 - (NORB / delta) * u_mills_var      # eta -> 0
    static_ladder = NORB / (-delta + 1j * np.array(ETA_STATIC))

    with open(outdir / "a1_two_level.nml", "w") as fh:
        write_group(fh, "a1_inputs", [
            ("norb", NORB), ("delta", delta), ("eta", ETA),
            ("amplitude_rule", "bands are (mu, spin); band (mu,s) has a = 1 at (mu, s), else 0"),
            ("e_up", 0.0), ("e_dn", delta), ("f_up", 1.0), ("f_dn", 0.0),
            ("u_test", u_test), ("mills_factor", mills_factor),
            ("nomega", omega.size), ("omega", omega),
            ("neta_static", len(ETA_STATIC)), ("eta_static", np.array(ETA_STATIC)),
        ])
        write_group(fh, "a1_expected", [
            ("moment", m), ("u_goldstone", u_gold),
            ("chi0_static_eta0", -NORB / delta),
            ("chi0_static_ladder_re", static_ladder.real),
            ("chi0_static_ladder_im", static_ladder.imag),
            ("pole", pole), ("pole_weight", float(NORB)),
            ("u_mills_variant", u_mills_var),
            ("residual_mills_variant", resid_mills_var),
            ("gap_mills_variant", resid_mills_var * delta),
            ("chi0_re", chi0.real), ("chi0_im", chi0.imag),
            ("chi_re", chi.real), ("chi_im", chi.imag),
            ("spectral", -chi.imag / np.pi),
        ])
    print(f"  pole {pole:.6f} Ry, Mills-variant residual {resid_mills_var:.6f}")


# ----------------------------------------------------------------------------
# A2: self-consistent single band, 1-D chain, NORB degenerate copies
# ----------------------------------------------------------------------------
def a2_ground_state(nk, t, filling, u, kt):
    k = 2.0 * np.pi * np.arange(nk) / nk          # lattice constant 1
    w = np.full(nk, 1.0 / nk)
    eps = -2.0 * t * np.cos(k)
    target = filling * NORB                        # electrons per site
    m = target                                     # start saturated
    for _ in range(2000):
        dlt = u * m                                # splitting e_dn - e_up
        eu, ed = eps - 0.5 * dlt, eps + 0.5 * dlt
        def nerr(ef):
            return NORB * (w * (fermi(eu, ef, kt) + fermi(ed, ef, kt))).sum() - target
        ef = bisect(nerr, eps.min() - dlt - 1.0, eps.max() + dlt + 1.0)
        m_new = NORB * (w * (fermi(eu, ef, kt) - fermi(ed, ef, kt))).sum()
        if abs(m_new - m) < 1e-15:
            m = m_new
            break
        m = 0.5 * m + 0.5 * m_new
    dlt = u * m
    eu, ed = eps - 0.5 * dlt, eps + 0.5 * dlt
    return dict(k=k, w=w, eps=eps, ef=ef, m=m, dlt=dlt, eu=eu, ed=ed,
                fu=fermi(eu, ef, kt), fd=fermi(ed, ef, kt))


def a2_chi0(gs, q, t, omega, eta, kt):
    """chi0(q, omega) per site; transitions up(k) -> dn(k+q), NORB copies."""
    kq = gs["k"] + q
    edq = -2.0 * t * np.cos(kq) + 0.5 * gs["dlt"]
    fdq = fermi(edq, gs["ef"], kt)
    weight = NORB * (gs["fu"] - fdq)
    de = gs["eu"] - edq
    chi0 = lehmann_pairs(gs["w"], de, weight, omega, eta)
    static0 = lehmann_static_eta0(gs["w"], gs["fu"], fdq, gs["eu"], edq, kt,
                                  np.full_like(weight, float(NORB)))
    return chi0, static0, edq, fdq, de, weight


def a2_magnon(gs, q, t, u, kt):
    """Root of 1 + U chi0(q, omega) on the real axis at eta = 0, below the continuum."""
    _, _, edq, fdq, de, weight = a2_chi0(gs, q, t, np.array([0.0]), 0.0, kt)
    wcont = float((-de).min())                     # lowest transition energy
    def g(om):
        return 1.0 + u * float((gs["w"] * weight / (om + de)).sum())
    if g(0.0) <= 0.0:
        return float("nan"), wcont                 # unstable at this q
    hi = wcont * (1.0 - 1e-12)
    if g(hi) > 0.0:
        return float("nan"), wcont                 # no root below the continuum
    return bisect(g, 0.0, hi), wcont


def model_a2(outdir, nk=400, t=0.05, filling=0.15, u=0.02, kt=0.002):
    print("A2 self-consistent single band")
    gs = a2_ground_state(nk, t, filling, u, kt)
    omega = np.linspace(-0.01, 0.04, 1001)
    qs = [2.0 * np.pi * j / nk for j in (0, 4, 10, 20, 40)]   # mesh-commensurate
    print(f"  E_F {gs['ef']:.12f} Ry, M {gs['m']:.12f}, Delta {gs['dlt']:.6f} Ry")

    with open(outdir / "a2_single_band.nml", "w") as fh:
        write_group(fh, "a2_inputs", [
            ("norb", NORB), ("nk", nk), ("t", t), ("filling", filling),
            ("amplitude_rule", "one site; bands are (mu, spin); band (mu,s) has a = 1 at (mu, s), else 0"),
            ("array_dims", "k(nk), w(nk), e_up(nk), e_dn(nk), f_up(nk), f_dn(nk); omega(nomega)"),
            ("u", u), ("kt", kt), ("eta", ETA),
            ("nomega", omega.size), ("omega", omega),
            ("neta_static", len(ETA_STATIC)), ("eta_static", np.array(ETA_STATIC)),
            ("k", gs["k"]), ("w", gs["w"]),
            ("e_up", gs["eu"]), ("e_dn", gs["ed"]),
            ("f_up", gs["fu"]), ("f_dn", gs["fd"]),
            ("nq", len(qs)),
        ])
        write_group(fh, "a2_ground_expected", [
            ("ef", gs["ef"]), ("moment", gs["m"]), ("splitting", gs["dlt"]),
            ("u_goldstone_exact", u), ("u_mills", gs["dlt"] / gs["m"]),
        ])
        for iq, q in enumerate(qs, start=1):
            chi0, st0, edq, fdq, de, weight = a2_chi0(gs, q, t, omega, ETA, kt)
            chi = chi0 / (1.0 + chi0 * u)
            ladder = np.array([lehmann_pairs(gs["w"], de, weight, np.array([0.0]), e)[0]
                               for e in ETA_STATIC])
            mag, wcont = a2_magnon(gs, q, t, u, kt)
            wm = window_moment(gs["w"], de, weight, ETA, omega[0], omega[-1])
            full = float((gs["w"] * weight).sum())        # full-line zeroth moment
            if iq == 1:
                check("Goldstone: chi0(0,0) U M + M, relative",
                      (st0 * u * gs["m"] + gs["m"]) / gs["m"], 1e-12)
                check("zeroth moment over the full line minus M, relative",
                      (full - gs["m"]) / gs["m"], 1e-12)
            print(f"  q={q:.5f}: magnon {mag:.8f} Ry, continuum edge {wcont:.6f} Ry, "
                  f"chi0(q,0) eta=0 {st0:.8f}")
            write_group(fh, "a2_q", [
                ("iq", iq), ("q", q),
                ("e_dn_kq", edq), ("f_dn_kq", fdq),
                ("chi0_re", chi0.real), ("chi0_im", chi0.imag),
                ("chi_re", chi.real), ("chi_im", chi.imag),
                ("chi0_static_eta0", st0),
                ("chi0_static_ladder_re", ladder.real),
                ("chi0_static_ladder_im", ladder.imag),
                ("magnon_eta0", mag), ("continuum_edge", wcont),
                ("chi0_window_moment", wm), ("chi0_full_moment", full),
            ])
    return gs


# ----------------------------------------------------------------------------
# A3: A2 on a doubled cell (sites at x = 0 and x = 1, cell length 2)
# ----------------------------------------------------------------------------
def cell_bands(kc, t, dlt, spin_sign):
    """Eigenvalues and site amplitudes of the 2x2 cell Hamiltonian, periodic gauge."""
    nkc = kc.size
    e = np.empty((nkc, 2))
    v = np.empty((nkc, 2, 2), dtype=complex)       # (k, site, band)
    for j, K in enumerate(kc):
        h01 = -t * (1.0 + np.exp(-2j * K))
        h = np.array([[0.0, h01], [np.conj(h01), 0.0]]) + spin_sign * 0.5 * dlt * np.eye(2)
        ev, vec = np.linalg.eigh(h)
        e[j], v[j] = ev, vec
    return e, v


def model_a3(outdir, gs, t=0.05, kt=0.002):
    print("A3 doubled cell")
    # Goldstone-consistent U for one orbital per site: splitting / moment per orbital
    u = gs["dlt"] / (gs["m"] / NORB)
    nk = gs["k"].size
    nkc = nk // 2
    kc = 2.0 * np.pi * np.arange(nkc) / nk         # cell BZ [0, pi), folds exactly
    wc = np.full(nkc, 1.0 / nkc)
    gsup = np.pi
    rng = np.random.default_rng(20261004)
    omega = np.linspace(-0.01, 0.04, 501)
    qs = [2.0 * np.pi * j / nk for j in (0, 4, 10)]

    def amplitudes(kpts):
        """Bands ordered (up band 1, up band 2, dn band 1, dn band 2) x NORB_A3 copies.

        a(band, mu, site, spin); random phase per band (gauge test).
        """
        eu, vu = cell_bands(kpts, t, gs["dlt"], -1.0)
        ed, vd = cell_bands(kpts, t, gs["dlt"], +1.0)
        nb = 4 * NORB_A3
        e = np.empty((kpts.size, nb))
        a = np.zeros((kpts.size, nb, NORB_A3, 2, 2), dtype=complex)
        for mu in range(NORB_A3):
            for b in range(2):
                ph = np.exp(2j * np.pi * rng.random((kpts.size, 2)))
                iu = 4 * mu + b
                idn = 4 * mu + 2 + b
                e[:, iu], e[:, idn] = eu[:, b], ed[:, b]
                a[:, iu, mu, :, 0] = vu[:, :, b] * ph[:, 0:1]
                a[:, idn, mu, :, 1] = vd[:, :, b] * ph[:, 1:2]
        return e, a

    e_k, a_k = amplitudes(kc)
    f_k = fermi(e_k, gs["ef"], kt)

    with open(outdir / "a3_doubled_cell.nml", "w") as fh:
        write_group(fh, "a3_inputs", [
            ("norb", NORB_A3), ("nsite", 2), ("nband", 4 * NORB_A3), ("nk", nkc),
            ("array_dims", "e(nk,nband), f(nk,nband), a_re/a_im(nk,nband,norb,nsite,2); spin 1=up 2=dn"),
            ("gauge", "periodic gauge, random phase per band and k-point"),
            ("u", u), ("kt", kt), ("eta", ETA), ("ef", gs["ef"]),
            ("nomega", omega.size), ("omega", omega),
            ("k", kc), ("w", wc), ("e", e_k), ("f", f_k),
            ("a_re", a_k.real), ("a_im", a_k.imag),
            ("nq", len(qs)),
        ])
        for iq, Q in enumerate(qs, start=1):
            e_kq, a_kq = amplitudes(kc + Q)
            f_kq = fermi(e_kq, gs["ef"], kt)
            # cell chi0_ij from the spec formula, all band pairs
            chi0 = np.zeros((omega.size, 2, 2), dtype=complex)
            for j in range(nkc):
                # T_i^{nm} = sum_mu conj(a^n_{i mu up}) a^m_{i mu dn}  -> (n, m, site)
                tt = (np.conj(a_k[j][:, None, :, :, 0])
                      * a_kq[j][None, :, :, :, 1]).sum(axis=2)
                fn = f_k[j][:, None] - f_kq[j][None, :]
                de = e_k[j][:, None] - e_kq[j][None, :]
                num = wc[j] * fn[..., None, None] * tt[..., :, None] * np.conj(tt[..., None, :])
                den = omega[:, None, None] + de[None, :, :] + 1j * ETA
                chi0 += np.einsum("wnm,nmij->wij", 1.0 / den, num)
            ident = np.eye(2)
            det = np.array([np.linalg.det(ident + c * u) for c in chi0])
            tr_chi = np.array([np.trace(np.linalg.solve(ident + c * u, c)) for c in chi0])
            tr_l = -tr_chi.imag / np.pi
            # primitive references at Q and Q + G_super (the oracle)
            c1 = a2_chi0(gs, Q, t, omega, ETA, kt)[0] / NORB * NORB_A3
            c2 = a2_chi0(gs, Q + gsup, t, omega, ETA, kt)[0] / NORB * NORB_A3
            det_ref = (1.0 + u * c1) * (1.0 + u * c2)
            tr_ref = c1 / (1.0 + u * c1) + c2 / (1.0 + u * c2)
            scale = np.max(np.abs(tr_ref))
            check(f"Q={Q:.4f}: cell tr chi vs primitive chi(Q)+chi(Q+G)",
                  np.max(np.abs(tr_chi - tr_ref)) / scale, 1e-11)
            check(f"Q={Q:.4f}: cell det(I+chi0 U) vs primitive product",
                  np.max(np.abs(det - det_ref)) / np.max(np.abs(det_ref)), 1e-11)
            write_group(fh, "a3_q", [
                ("iq", iq), ("q", Q), ("g_super", gsup),
                ("e_kq", e_kq), ("f_kq", f_kq),
                ("a_kq_re", a_kq.real), ("a_kq_im", a_kq.imag),
                ("chi0_prim_q_re", c1.real), ("chi0_prim_q_im", c1.imag),
                ("chi0_prim_qg_re", c2.real), ("chi0_prim_qg_im", c2.imag),
                ("tr_chi_re", tr_ref.real), ("tr_chi_im", tr_ref.imag),
                ("tr_spectral", -tr_ref.imag / np.pi),
                ("det_re", det_ref.real), ("det_im", det_ref.imag),
            ])


def main():
    outdir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("out")
    outdir.mkdir(parents=True, exist_ok=True)
    model_a1(outdir)
    gs = model_a2(outdir)
    model_a3(outdir, gs)
    print(f"written to {outdir}/")


if __name__ == "__main__":
    main()
